# Generated by Django 6.1 on 2026-09-01 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        # Drop existing tables that may have been partially created
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "blog_profile" CASCADE;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "blog_blog_details" CASCADE;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "blog_user" CASCADE;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "blog_tags" CASCADE;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "blog_category" CASCADE;',
            reverse_sql='',
        ),
        # Now create the models
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['id'], 'verbose_name': 'Blog'},
        ),
        migrations.CreateModel(
            name='Blog_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('blog', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='blog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.user'),
        ),
    ]
